definitions:
  http.AddUserReq:
    properties:
      firstName:
        description: 名
        type: string
      lastName:
        description: 姓
        type: string
      username:
        description: 用户名
        type: string
    type: object
  http.AddUserRsp:
    properties:
      first_name:
        description: 名
        type: string
      id:
        description: id
        type: integer
      last_name:
        description: 姓
        type: string
      username:
        description: 用户名
        type: string
    type: object
  http.GetUserRsp:
    properties:
      first_name:
        description: 名
        type: string
      id:
        description: id
        type: integer
      last_name:
        description: 姓
        type: string
      username:
        description: 用户名
        type: string
    type: object
  http.Response:
    properties:
      code:
        description: 错误码
        type: integer
      data:
        description: 数据
      message:
        description: 错误消息
        type: string
    type: object
info:
  contact: {}
paths:
  /profile:
    get:
      consumes:
      - application/json
      description: 获取当前登录用户信息
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/http.Response'
            - properties:
                data:
                  $ref: '#/definitions/http.GetUserRsp'
              type: object
      security:
      - ApiKeyAuth: []
      summary: 获取当前登录用户信息
      tags:
      - user
  /user:
    get:
      consumes:
      - application/json
      description: 获取指定用户信息
      parameters:
      - description: 用户 id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/http.Response'
            - properties:
                data:
                  $ref: '#/definitions/http.GetUserRsp'
              type: object
      summary: 获取指定用户信息
      tags:
      - user
    post:
      consumes:
      - application/json
      description: 添加用户信息
      parameters:
      - description: 用户信息
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/http.AddUserReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/http.Response'
            - properties:
                data:
                  $ref: '#/definitions/http.AddUserRsp'
              type: object
      summary: 添加用户信息
      tags:
      - user
swagger: "2.0"
