// Code generated by https://github.com/smartwalle/protoc-gen-sm. DO NOT EDIT.

package grpc

func NewGetUserReq() *GetUserReq {
	return &GetUserReq{}
}

func NewGetUserRsp() *GetUserRsp {
	return &GetUserRsp{}
}
