// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: user.proto

/*
Package grpc is a generated protocol buffer package.

It is generated from these files:
	user.proto

It has these top-level messages:
	GetUserReq
	GetUserRsp
*/
package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for User service

type UserService interface {
	GetUserWithId(ctx context.Context, in *GetUserReq, opts ...client.CallOption) (*GetUserRsp, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "grpc"
	}
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) GetUserWithId(ctx context.Context, in *GetUserReq, opts ...client.CallOption) (*GetUserRsp, error) {
	req := c.c.NewRequest(c.name, "User.GetUserWithId", in)
	out := new(GetUserRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for User service

type UserHandler interface {
	GetUserWithId(context.Context, *GetUserReq, *GetUserRsp) error
}

func RegisterUserHandler(s server.Server, hdlr UserHandler, opts ...server.HandlerOption) error {
	type user interface {
		GetUserWithId(ctx context.Context, in *GetUserReq, out *GetUserRsp) error
	}
	type User struct {
		user
	}
	h := &userHandler{hdlr}
	return s.Handle(s.NewHandler(&User{h}, opts...))
}

type userHandler struct {
	UserHandler
}

func (h *userHandler) GetUserWithId(ctx context.Context, in *GetUserReq, out *GetUserRsp) error {
	return h.UserHandler.GetUserWithId(ctx, in, out)
}
